---
- name: Install Zabbix repository, MySQL Server, and update packages
  hosts: zabbix_server
  become: yes
  
  tasks:
    - name: Download Zabbix repository package
      get_url:
        url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
        dest: /home/{{ target_username }}/zabbix-release_6.4-1+ubuntu22.04_all.deb

    - name: Install Zabbix repository package
      apt:
        deb: /home/{{ target_username }}/zabbix-release_6.4-1+ubuntu22.04_all.deb

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix server, frontend, and related packages
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    - name: Update apt cache before MySQL installation
      apt:
        update_cache: yes

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Create Zabbix database, user, and set privileges using expect
      expect:
        command: mysql -uroot -p
        responses:
          "Enter password:": ""
          "mysql>": |
            create database zabbix character set utf8mb4 collate utf8mb4_bin;
            create user zabbix@localhost identified by '{{ zabbix_password }}';
            grant all privileges on zabbix.* to zabbix@localhost;
            set global log_bin_trust_function_creators = 1;
            quit;

    - name: Copy the Zabbix Script Zip File
      command: cp /usr/share/zabbix-sql-scripts/mysql/server.sql.gz /home/{{ target_username }}/

    - name: Unzip Zabbix SQL Script
      command: gunzip /home/{{ target_username }}/server.sql.gz

    - name: Import SQL Script file into MySQL database
      shell: mysql -uzabbix -p{{ zabbix_password }} zabbix < /home/{{ target_username }}/server.sql

    - name: Create Zabbix database, user, and set privileges using expect
      expect:
        command: mysql -uroot -p
        responses:
          "Enter password:": ""
          "mysql>": |
            set global log_bin_trust_function_creators = 0;
            quit;

    - name: Copy Configuration Template File
      template:
        src: /home/{{ control_username }}/zabbix_server.conf.j2
        dest: /etc/{{ target_username }}/zabbix_server.conf
        mode: "0600"

    - name: Restart Zabbix Server, Zabbix Agent, and Apache2
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2

    - name: Enable Zabbix Server, Zabbix Agent, and Apache2
      systemd:
        name: "{{ item }}"
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2
