---
- name: Install and configure Zabbix repository and agent
  hosts: zabbix_agents
  become: yes  # Use become to get root privileges
  vars:
    download_dest: "/home/{{ target_username }}"
  tasks:
    - name: Download Zabbix release package
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
        dest: "{{ download_dest }}/zabbix-release_6.4-1+ubuntu22.04_all.deb"
        mode: '0644'

    - name: Install Zabbix release package
      ansible.builtin.apt:
        deb: "{{ download_dest }}/zabbix-release_6.4-1+ubuntu22.04_all.deb"

    - name: Update the apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install zabbix-agent
      ansible.builtin.apt:
        name: zabbix-agent
        state: present
        update_cache: yes

    - name: Upload Jinja2 template file
      ansible.builtin.template:
        src: "/home/{{ control_username }}/zabbix_agentd.conf.j2"
        dest: "/etc/zabbix/zabbix_agentd.conf"  # Specify the destination path on the target host
        owner: root  # Specify the owner of the uploaded file
        group: root
        mode: '0644'

    - name: Ensure zabbix-agent is restarted and enabled
      ansible.builtin.systemd:
        name: zabbix-agent
        state: restarted
        enabled: yes
