---
- name: Add Blackbox Task
  hosts: prometheus
  tasks:
    - name: Add blackbox scrape config
      action: ansible.builtin.lineinfile
      args:
        path: /usr/local/bin/prometheus/prometheus.yml
        insertafter: '^  - targets: \["localhost:9090"\]$'
        line:  "\n  - job_name: 'blackbox'\n    metrics_path: /probe\n    params:\n      module: [http_2xx]\n    static_configs:\n      - targets:\n    relabel_configs:\n      - source_labels: [__address__]\n        target_label: __param_target\n      - source_labels: [__param_target]\n        target_label: instance\n      - target_label: __address__\n        replacement: localhost:9115" 
