---
- name: Install and Configure Wazuh Indexer
  hosts: wazuh
  become: yes

  environment:
    NODE_NAME: "node-1"
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - gnupg
        - apt-transport-https
        - curl

    - name: Download wazuh-certs-tool.sh
      ansible.builtin.get_url:
        url: https://packages.wazuh.com/4.7/wazuh-certs-tool.sh
        dest: /home/{{ target_username }}/wazuh-certs-tool.sh
        mode: '0755'  # Ensure execute permission

    - name: Copy Configuration File
      template:
        src: /home/{{ control_username }}/config.yml.j2  # Path to your local Jinja2 template file
        dest: /home/{{ target_username }}/config.yml  # Destination path and new name on the remote machine
        mode: 0644

    - name: Run wazuh-certs-tool.sh -A
      ansible.builtin.shell: bash /home/{{ target_username }}/wazuh-certs-tool.sh -A

    - name: Create wazuh-certificates.tar
      ansible.builtin.shell: tar -cvf /home/{{ target_username }}/wazuh-certificates.tar -C /home/{{ target_username }}/wazuh-certificates/ .

    - name: Remove wazuh-certificates directory
      ansible.builtin.shell: rm -rf /home/{{ target_username }}/wazuh-certificates

    - name: Import Wazuh GPG key
      ansible.builtin.shell: |
        curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg

    - name: Add Wazuh repository
      ansible.builtin.shell: |
        echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list

    - name: Update package information
      apt:
        update_cache: yes

    - name: Install wazuh-indexer package
      ansible.builtin.shell: apt-get -y install wazuh-indexer

    - name: Replace network.host in opensearch.yml
      ansible.builtin.replace:
        path: /etc/wazuh-indexer/opensearch.yml
        regexp: '^network.host: "0.0.0.0"'
        replace: 'network.host: "{{ node_ip }}"'
        backup: yes

    - name: Make directory for certificates
      ansible.builtin.file:
        path: /etc/wazuh-indexer/certs
        state: directory

    - name: Extract certificates tar file
      ansible.builtin.command:
        cmd: tar -xf /home/{{ target_username }}/wazuh-certificates.tar -C /etc/wazuh-indexer/certs/ ./$NODE_NAME.pem ./$NODE_NAME-key.pem ./admin.pem ./admin-key.pem ./root-ca.pem
      args:
        creates: /etc/wazuh-indexer/certs/indexer.pem  # Specify the certificate file path

    - name: Rename indexer certificate
      ansible.builtin.command:
        cmd: mv -n /etc/wazuh-indexer/certs/$NODE_NAME.pem /etc/wazuh-indexer/certs/indexer.pem
      args:
        creates: /etc/wazuh-indexer/certs/indexer-key.pem  # Specify the certificate key file path
      changed_when: false  # Avoid indicating changed status if file already exists

    - name: Rename indexer key
      ansible.builtin.command:
        cmd: mv -n /etc/wazuh-indexer/certs/$NODE_NAME-key.pem /etc/wazuh-indexer/certs/indexer-key.pem
      changed_when: false  # Avoid indicating changed status if file already exists

    - name: Set permissions on certs directory
      ansible.builtin.file:
        path: /etc/wazuh-indexer/certs
        mode: "0500"

    - name: Set permissions on certificate files
      ansible.builtin.file:
        path: "/etc/wazuh-indexer/certs/{{ item }}"
        mode: "0400"
      loop:
        - admin-key.pem
        - admin.pem
        - indexer-key.pem
        - indexer.pem
        - root-ca.pem

    - name: Change ownership of certs directory
      ansible.builtin.file:
        path: /etc/wazuh-indexer/certs
        owner: wazuh-indexer
        group: wazuh-indexer
        recurse: yes

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable Wazuh Indexer service
      ansible.builtin.systemd:
        name: wazuh-indexer
        enabled: yes

    - name: Start Wazuh Indexer service
      ansible.builtin.systemd:
        name: wazuh-indexer
        state: started

    - name: Run indexer-security-init.sh script
      ansible.builtin.command: /usr/share/wazuh-indexer/bin/indexer-security-init.sh
